spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
         uri: https://gitee.com/zeyi_chen/config-repo
         username: 
         password: 
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9999
