spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/order_sys?characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai #禁用https
  jpa:
    show-sql: true #展示sql 方便调试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
server:
  port: 8000